language: cpp
compiler:
    - g++
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - libboost-all-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - gcc
      - g++
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list scons &>/dev/null || brew install scons ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list boost &>/dev/null || brew install boost ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list openssl &>/dev/null || brew install openssl ; fi
cache:
  apt: true
script: scons install apps samples
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
