---
- name: Install freelan load test dependencies
  apt: name={{ item }} state=present
  with_items:
    - gdb
    - valgrind
    - screen
  become: yes
  become_method: sudo
  become_user: root

- name: Create nodes configuration directory
  file: dest={{ nodes_config_root }} state=directory

- name: Create CA directory
  file: dest={{ ca_root }} state=directory

- name: Create nodes scripts directory
  file: dest={{ scripts_root }} state=directory

- name: Create nodes certificates and private keys
  command: openssl req -new -nodes -x509 -subj "/CN={{ item.name }}" -days 3650 -keyout {{ nodes_config_root }}/{{ item.name }}.key -out {{ nodes_config_root }}/{{ item.name }}.crt -extensions v3_ca creates={{ nodes_config_root }}/{{ item.name }}.crt
  with_items: "{{ freelan_nodes }}"

- name: Create nodes configuration files
  template: src=configuration.cfg dest={{ nodes_config_root }}/{{ item.name }}.cfg
  with_items: "{{ freelan_nodes }}"

- name: Create scripts files
  template: src=launch-script.sh dest={{ scripts_root }}/{{ item.name }}.sh mode=755
  with_items: "{{ freelan_nodes }}"

- name: Create debug scripts files
  template: src=launch-debug-script.sh dest={{ scripts_root }}/debug-{{ item.name }}.sh mode=755
  with_items: "{{ freelan_nodes }}"

- name: Create detached scripts files
  template: src=launch-detached-script.sh dest={{ scripts_root }}/detached-{{ item.name }}.sh mode=755
  with_items: "{{ freelan_nodes }}"

- name: Create detached debug scripts files
  template: src=launch-detached-debug-script.sh dest={{ scripts_root }}/detached-debug-{{ item.name }}.sh mode=755
  with_items: "{{ freelan_nodes }}"

- name: Create all detached script file
  template: src=launch-all-script.sh dest={{ scripts_root }}/all.sh mode=755

- name: Create all detached debug script file
  template: src=launch-all-debug-script.sh dest={{ scripts_root }}/all-debug.sh mode=755
